version: '2'
services:
  nginx-react:
    image: coinlizard-fe:latest
    container_name: coinlizard-fe
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4200:4200
    environment:
      NODE_ENV: production
